version: "3"

services:
  app:
    build: .
    container_name: compliance-api-app
    command: uvicorn src.main:app --host 0.0.0.0 --port 15400 --reload
    ports:
      - 8000:15400
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    container_name: compliance-api-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: compliance-api-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin-data: