name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the stack
        run: docker-compose up -d

      - name: Test API
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" http://your-api-endpoint.com/health)
          cat response.txt
          if [ "$response" -ne 200 ]; then
            echo "API is not responding correctly"
            exit 1
          fi
          echo "API is responding correctly"