name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: docker run --network container:compliance-api-app appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/api/v1/hosts/
